AWSTemplateFormatVersion: 2010-09-09
Description: 'Online Pharamacy infrastructure for Hakon Sorums Master Thesis fall 2022'


Parameters: 
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.small
    AllowedValues: [t2.nano, t2.micro, t2.small, t2.medium, t2.large, t2.xlarge, t2.2xlarge,
      t3.nano, t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge,
      m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
      m5.large, m5.xlarge, m5.2xlarge, m5.4xlarge,
      c5.large, c5.xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge,
      g3.8xlarge,
      r5.large, r5.xlarge, r5.2xlarge, r5.4xlarge, r3.12xlarge,
      i3.xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge,
      d2.xlarge, d2.2xlarge, d2.4xlarge, d2.8xlarge]
    ConstraintDescription: must be a valid EC2 instance type.
  HttpsLocation:
    Description: The IP address range that can be used to access the web-shop
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.  
  
Resources:  
  PharmacyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: --.--.--.--/--
      EnableDnsSupport: true
      Tags:
        - Key: keyname
          Value: value

  publicSubAz1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: zone-id
      VpcId: vpc-id
      CidrBlock: --.--.--.--/--
      Tags:
        - Key: trustzone
          Value: value

  publicSubAz2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: zone-id
      VpcId: vpc-id
      CidrBlock: --.--.--.--/--
      Tags:
        - Key: trustzone
          Value: value

  privateSubFEAz1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: zone-id
      VpcId: vpc-id
      CidrBlock: --.--.--.--/--
      Tags:
        - Key: trustzone
          Value: value

    privateSubFEAz2:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: zone-id
        VpcId: vpc-id
        CidrBlock: --.--.--.--/--
        Tags:
          - Key: trustzone
            Value: value

    privateSubBEAz1:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: zone-id
        VpcId: vpc-id
        CidrBlock: --.--.--.--/--
        Tags:
          - Key: trustzone
            Value: value

    privateSubBEAz2:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: zone-id
        VpcId: vpc-id
        CidrBlock: --.--.--.--/--
        Tags:
          - Key: keyname
            Value: value

    privateSubDB1:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: zone-id
        VpcId: vpc-id
        CidrBlock: --.--.--.--/--
        Tags:
          - Key: keyname
            Value: value

    privateSubDB2:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: zone-id
        VpcId: vpc-id
        CidrBlock: --.--.--.--/--
        Tags:
          - Key: keyname
            Value: value
    
    externalALBSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: 
        GroupDescription: 
        VpcId:
        SecurityGroupIngress:
          - Security Group Rule
        SecurityGroupEgress:
          - Security Group Rule
        Tags:
          - Key:
            Value:

    internalALBSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: 
        GroupDescription: 
        VpcId:
        SecurityGroupIngress:
          - Security Group Rule
        SecurityGroupEgress:
          - Security Group Rule
        Tags:
          - Key:
            Value:

    frontEndSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: 
        GroupDescription: 
        VpcId:
        SecurityGroupIngress:
          - Security Group Rule
        SecurityGroupEgress:
          - Security Group Rule
        Tags:
          - Key:
            Value:
    
    backEndSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: 
        GroupDescription: 
        VpcId:
        SecurityGroupIngress:
          - Security Group Rule
        SecurityGroupEgress:
          - Security Group Rule
        Tags:
          - Key:
            Value:
    dbSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupName: 
        GroupDescription: 
        VpcId:
        SecurityGroupIngress:
          - Security Group Rule
        SecurityGroupEgress:
          - Security Group Rule
        Tags:
          - Key:
            Value:
    
    publicALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties: 
        IpAddressType: ipv4
        Name: publicRequestLoadbalancing
        Scheme: String
        SecurityGroups: 
          - String
        SubnetMappings: 
          - SubnetMapping
        Subnets: 
          - String
        Tags: 
          - Tag
        Type: String
    
    frontEndLaunchTemplate:
      Type: AWS::EC2::LaunchTemplate
      Properties:
        LaunchTemplateName: !Sub ${AWS::StackName}-front-end-launch-template
        LaunchTemplateData: 
          ImageID: !Ref LatestAmiId
          InstanceType: !Ref InstanceType

    backEndLaunchTemplate:
      Type: AWS::EC2::LaunchTemplate
      Properties:
        LaunchTemplateName: !Sub ${AWS::StackName}-back-end-launch-template
        LaunchTemplateData: 
          ImageID: !Ref LatestAmiId
          InstanceType: !Ref InstanceType
    
    frontEndASG:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        AvailabilityZones: !GetAZs ''
        LaunchTemplate:
          LaunchTemplateId: !Ref frontEndLaunchTemplate
          Version: !GetATT frontEndLaunchTemplate.LatestVersionNumber
        MaxSize: '4'
        MinSize: '2'
        DesiredCapacity: '2'
        Tags:
          - Key: keyname
            Value: value
            PropagateAtLaunch: True|False  
    
    backEndASG:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        AvailabilityZones: !GetAZs ''
        LaunchTemplate: 
          LaunchTemplateId: !Ref backEndLaunchTemplate
          Version: !GetATT backEndLaunchTemplate.LatestVersionNumber
        MaxSize: '4'
        MinSize: '2'
        DesiredCapacity: '2'
        Tags:
          - Key: keyname
            Value: value
            PropagateAtLaunch: True|False
    
    